/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DerivativesRouteImport } from './routes/derivatives'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SpotRouteImport } from './routes/spot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivativesRoute = DerivativesRouteImport.update({
  id: '/derivatives',
  path: '/derivatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotRoute = SpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/spot': typeof SpotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/spot': typeof SpotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/derivatives': typeof DerivativesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/register': typeof RegisterRoute
  '/spot': typeof SpotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/derivatives'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/register'
    | '/spot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/derivatives'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/register'
    | '/spot'
  id:
    | '__root__'
    | '/'
    | '/derivatives'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/register'
    | '/spot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DerivativesRoute: typeof DerivativesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  RegisterRoute: typeof RegisterRoute
  SpotRoute: typeof SpotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derivatives': {
      id: '/derivatives'
      path: '/derivatives'
      fullPath: '/derivatives'
      preLoaderRoute: typeof DerivativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot': {
      id: '/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DerivativesRoute: DerivativesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  RegisterRoute: RegisterRoute,
  SpotRoute: SpotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
